### ISSUE TITLE
Update Readme URLS

### ISSUE THREAD

**Issue by UM-RMeeker** [ebardelli/VideoTranscriber#1]
Trailing slash on the models url results in a 403. Recommend replacing with:

- Get the ML speech recognition model here: https://alphacephei.com/vosk/models. Make sure to update the model name to the one you selected in the python file. At time of writing, there are three models for English: `0.15` (small model), `0.22`, and `0.22-lgraph`. All three seem to work fine.
  - `wget "https://alphacephei.com/vosk/models/vosk-model-small-en-us-0.15.zip"`
  - `wget "https://alphacephei.com/vosk/models/vosk-model-en-us-0.22.zip"`
  - `wget "https://alphacephei.com/vosk/models/vosk-model-en-us-0.22-lgraph.zip"`

**Comment by ebardelli** [comment]
Good point. I have updated the readme.

**Comment by UM-RMeeker** [comment]
Please also add, since your code requires the speaker module:

`wget "https://alphacephei.com/vosk/models/vosk-model-spk-0.4.zip"`

**Comment by ebardelli** [comment]
I moved the downloads to a python script. That should take care of downloading and unzipping the models in the `Models/` directory with minimal user interaction. Let me know if that works!
